---
name: build-examples

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-examples:
    defaults:
      run:
        working-directory: examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build with Maven
        run: mvn verify
